version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    command: "sh -c 'alembic upgrade head && python3 main.py'"
    networks:
      - app-network

networks:
  app-network:
