""" igrationV2

Revision ID: 914fb9aaf535
Revises: 421ac45e5cc5
Create Date: 2024-03-03 00:34:36.933487

"""
from typing import Sequence, Union
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '914fb9aaf535'
down_revision: Union[str, None] = '421ac45e5cc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_photos_id', table_name='user_photos')
    op.drop_table('user_photos')
    op.add_column('users', sa.Column('photo', sqlalchemy_utils.types.url.URLType(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'photo')
    op.create_table('user_photos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('photo_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_photos_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_photos_pkey')
    )
    op.create_index('ix_user_photos_id', 'user_photos', ['id'], unique=False)
    # ### end Alembic commands ###
